apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrds.toto.gaubert.eu
spec:
  conversion:
    strategy: None
  group: toto.gaubert.eu
  names:
    kind: TestCrd
    listKind: TestCrdList
    plural: testcrds
    singular: testcrd
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
